/**
 * Forge SDK
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * Contact: forge.help@autodesk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

module.exports = (function () {
  'use strict';

  var ApiClient = require('../ApiClient');



  /**
   * The BaseAttributesCreatedUpdatedAttributes model module.
   * @module model/BaseAttributesCreatedUpdatedAttributes
   */

  /**
   * Constructs a <code>BaseAttributesCreatedUpdatedAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BaseAttributesCreatedUpdatedAttributes} obj Optional instance to populate.
   * @return {module:model/BaseAttributesCreatedUpdatedAttributes} The populated <code>BaseAttributesCreatedUpdatedAttributes</code> instance.
   */
  var constructFromObject = function (data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('createTime')) {
        obj.createTime = ApiClient.convertToType(data.createTime, 'Date');
      }
      if (data.hasOwnProperty('createUserId')) {
        obj.createUserId = ApiClient.convertToType(data.createUserId, 'String');
      }
      if (data.hasOwnProperty('lastModifiedTime')) {
        obj.lastModifiedTime = ApiClient.convertToType(data.lastModifiedTime, 'Date');
      }
      if (data.hasOwnProperty('lastModifiedUserId')) {
        obj.lastModifiedUserId = ApiClient.convertToType(data.lastModifiedUserId, 'String');
      }
    }
    return obj;
  };

  /**
   * Constructs a new <code>BaseAttributesCreatedUpdatedAttributes</code>.
   * @alias module:model/BaseAttributesCreatedUpdatedAttributes
   * @class
   * @param createTime {Date} 
   * @param createUserId {String} 
   * @param lastModifiedTime {Date} 
   * @param lastModifiedUserId {String} 
   * @param {Object} theData The plain JavaScript object bearing properties of interest.
   * @param {module:model/BaseAttributesCreatedUpdatedAttributes} obj Optional instance to populate.
   */
  var exports = function (createTime, createUserId, lastModifiedTime, lastModifiedUserId, theData, obj) {
    var _this = this;

    _this.createTime = createTime;
    _this.createUserId = createUserId;
    _this.lastModifiedTime = lastModifiedTime;
    _this.lastModifiedUserId = lastModifiedUserId;

    return constructFromObject(theData, obj || _this);
  };

  /**
   * Constructs a <code>BaseAttributesCreatedUpdatedAttributes</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BaseAttributesCreatedUpdatedAttributes} obj Optional instance to populate.
   * @return {module:model/BaseAttributesCreatedUpdatedAttributes} The populated <code>BaseAttributesCreatedUpdatedAttributes</code> instance.
   */
  exports.constructFromObject = constructFromObject;

  /**
   * @member {Date} createTime
   */
  exports.prototype.createTime = undefined;
  /**
   * @member {String} createUserId
   */
  exports.prototype.createUserId = undefined;
  /**
   * @member {Date} lastModifiedTime
   */
  exports.prototype.lastModifiedTime = undefined;
  /**
   * @member {String} lastModifiedUserId
   */
  exports.prototype.lastModifiedUserId = undefined;



  return exports;
}());


