/**
 * Forge SDK
 * The Forge Platform contains an expanding collection of web service components that can be used with Autodesk cloud-based products or your own technologies. Take advantage of Autodesk’s expertise in design and engineering.
 *
 * Contact: forge.help@autodesk.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

module.exports = (function () {
  'use strict';

  var ApiClient = require('../ApiClient'),
    UserProfileProfileImages = require('./UserProfileProfileImages');



  /**
   * The UserProfile model module.
   * @module model/UserProfile
   */

  /**
   * Constructs a <code>UserProfile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserProfile} obj Optional instance to populate.
   * @return {module:model/UserProfile} The populated <code>UserProfile</code> instance.
   */
  var constructFromObject = function (data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('userId')) {
        obj.userId = ApiClient.convertToType(data.userId, 'String');
      }
      if (data.hasOwnProperty('userName')) {
        obj.userName = ApiClient.convertToType(data.userName, 'String');
      }
      if (data.hasOwnProperty('emailId')) {
        obj.emailId = ApiClient.convertToType(data.emailId, 'String');
      }
      if (data.hasOwnProperty('firstName')) {
        obj.firstName = ApiClient.convertToType(data.firstName, 'String');
      }
      if (data.hasOwnProperty('lastName')) {
        obj.lastName = ApiClient.convertToType(data.lastName, 'String');
      }
      if (data.hasOwnProperty('emailVerified')) {
        obj.emailVerified = ApiClient.convertToType(data.emailVerified, 'Boolean');
      }
      if (data.hasOwnProperty('2FaEnabled')) {
        obj['2FaEnabled'] = ApiClient.convertToType(data['2FaEnabled'], 'Boolean');
      }
      if (data.hasOwnProperty('profileImages')) {
        obj.profileImages = UserProfileProfileImages.constructFromObject(data.profileImages);
      }
    }
    return obj;
  };

  /**
   * Constructs a new <code>UserProfile</code>.
   * user Profile
   * @alias module:model/UserProfile
   * @class
   * @param {Object} theData The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserProfile} obj Optional instance to populate.
   */
  var exports = function (theData, obj) {
    var _this = this;

    return constructFromObject(theData, obj || _this);
  };

  /**
   * Constructs a <code>UserProfile</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/UserProfile} obj Optional instance to populate.
   * @return {module:model/UserProfile} The populated <code>UserProfile</code> instance.
   */
  exports.constructFromObject = constructFromObject;

  /**
   * The backend user ID of the profile
   * @member {String} userId
   */
  exports.prototype.userId = undefined;
  /**
   * The username chosen by the user
   * @member {String} userName
   */
  exports.prototype.userName = undefined;
  /**
   * The user’s email address
   * @member {String} emailId
   */
  exports.prototype.emailId = undefined;
  /**
   * The user’s first name
   * @member {String} firstName
   */
  exports.prototype.firstName = undefined;
  /**
   * The user’s last name
   * @member {String} lastName
   */
  exports.prototype.lastName = undefined;
  /**
   * The user’s email address has been verified or not
   * @member {Boolean} emailVerified
   */
  exports.prototype.emailVerified = undefined;
  /**
   * The user has enabled two-factor authentication or not
   * @member {Boolean} 2FaEnabled
   */
  exports.prototype['2FaEnabled'] = undefined;
  /**
   * @member {module:model/UserProfileProfileImages} profileImages
   */
  exports.prototype.profileImages = undefined;



  return exports;
}());


